# Generated by Django 3.1.2 on 2021-03-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socnet.users', verbose_name='Пользователь'),
        ),
    ]
